eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8080
spring:
  main:
     web-application-type: reactive
  application:
    name: "API-GATEWAY"
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      global-cors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
        add-to-simple-url-handler-mapping: true
      routes:
        - id: user-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/**
          filters:
            - RewritePath=/api/v1(?<segment>/?.*), $\{segment}

        - id: product-web-app
          uri: http://localhost:4000
          predicates:
            - Path=/ap1/v1/**
          filters:
            - RewritePath=/ap1/v1(?<segment>/?.*), $\{segment}

        - id: bank-service
          uri: http://localhost:8070
          predicates:
            - Path=/ap1/v1/**
          filters:
            - RewritePath=/ap1/v1(?<segment>/?.*), $\{segment}

        - id: transaction-service
          uri: http://localhost:8060
          predicates:
            - Path=/ap1/v1/**
          filters:
            - RewritePath=/ap1/v1(?<segment>/?.*), $\{segment}
