eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      global-cors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:/3000"
            allowedHeaders:
              - Content-Type
            allowedMethods: "*"
        add-to-simple-url-handler-mapping: true
  main:
    web-application-type: reactive
  application:
    name: "API-GATEWAY"
  datasource:
    url: "jdbc:mysql://localhost:3306/batondb"
    username: "root"
    password: "Chennai@123"